---
title: "05CalibrationModels_PLS_Loop_ARC"
output: html_document
date: "2023-07-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\_ two ways of doing predictions (1) with an existing model that was built some time ago and (2) in this case when you have the spectral and wet chem data and you have to develop the model

Reference data = wet chemistry data of the full 100 samples (being used to develop the model)

```{r}
library(dplyr)
library(prospectr)
library (globals)
library(stringr)
library(ggplot2)

setwd("/Users/vkarari/Library/CloudStorage/OneDrive-CGIAR/Documents/0All_Training/SA_ARC_Physical_Training_Aug-Sept22/Predictions-ARC_PLS")

#FUSI EDIT
#The file being uploaded here is lilely just the cleaned spectra on the 100 biochars (since they have the reference data that is being refernced later)
spectraldata=read.csv("/Users/vkarari/Library/CloudStorage/OneDrive-CGIAR/Documents/0All_Training/SA_ARC_Physical_Training_Aug-Sept22/ARC-MIR/ARC-MIR.csv")
rownames(spectraldata)<-spectraldata$SSN


#Remove metadata columns when using raw file
# names(spectraldata)
# spectraldata<-spectraldata[,-2:-17]

library("stringr")
#Ensure all the wavenumbers are rounded to one decimal place
names(spectraldata)=round(as.numeric(str_sub(names(spectraldata),2)),1)
names(spectraldata)[1] <- "SSN"

#Read reference data
df1=read.csv("/Users/vkarari/Library/CloudStorage/OneDrive-CGIAR/Documents/0All_Training/SA_ARC_Physical_Training_Aug-Sept22/ARC-Ref/ARC-Ref.csv")#[,c(1,8:29)]

rownames(df1)<-df1$SSN


##################################### Spectra pre-treatment ###################
#remove the CO2 region from all data
co2rem<-which((as.numeric(colnames(spectraldata[-1]))) < 2380 & (as.numeric(colnames(spectraldata[-1]))) > 2350)
spectraldata.f<-spectraldata[,-co2rem]

#Mean-centering function
center_colmeans <- function(x) {
  xcenter = colMeans(x)
  x - rep(xcenter, rep.int(nrow(x), ncol(x)))
}

#SavitzkyGolay pretreatment
spec_der<-as.data.frame(savitzkyGolay(spectraldata.f[,-1], w=17, p=2, m=1))

#Mean-centering
spec_der.mc_trt<-center_colmeans(spec_der)

spec_trt<-bind_cols(SSN=spectraldata$SSN,spec_der.mc_trt)

###############################################################################

#select only the common soil samples in spectral and wet chemie data
df.f<-df1[is.element(df1$SSN, spectraldata$SSN),]

# #Remove unwanted characters in the dataa
# df.f[sapply(df.f, grepl, pattern = "<")] <- "NA"
dnmrc <- df.f[,-1] %>% mutate_if(is.character, as.numeric)
df.f <- bind_cols(SSN = df.f[,1],dnmrc)

spectraldata.fin<-spectraldata[is.element(spectraldata$SSN, df.f$SSN),]

#Set splitting proportion for the calibration and validation data
set.seed(123)
pool=df.f[sample(nrow(df.f), round(0.3*nrow(df.f),0)), ]
pool<-pool[order(pool$SSN),]
poolid<-pool$SSN

##################### Random Forest Modelling #################################
library(randomForest)
library(caret)
library(pls)
#If package ithir is not available for your version of R
#Use the 3 below lines to install package ithir
# install.packages("devtools") 
# library(devtools)
# install_bitbucket("brendo1001/ithir/pkg") 
library(ithir)

#Available properties to predict
#Incase you want to predict only selected properties,
#get property position by running line 66. Remove hash sign between ")" and "["
#symbols on line 67. Edit properties position and run line 67.
#Always ensure position 1 in always included.
names(df1)
slprptr<-names(df1)[c(1:5,9:23)]

pred<-as.data.frame(spec_trt[,1])
colnames(pred)<-"SSN"

mdl.stats<-NULL#Model stats container

for(p in 2:length(slprptr)){
  
#Select properties to predict one at a time and remove NAs  
df.sel<-df.f %>% select(SSN, slprptr[p]) %>% na.omit

#Plot and print soil properties boxplots
boxplot(df.sel[,slprptr[p]], las=2, xlab = slprptr[p], ylab = "")
dir.create("Plots_Boxplots")
png(paste0(getwd(),"/Plots_Boxplots/",slprptr[p],".png"))
print(boxplot(df.sel[,slprptr[p]], las=2, xlab = slprptr[p], ylab = ""))
dev.off()

# #Split samples inside loop for variables with many NAs
# #Set splitting proportion for the calibration and validation data
# set.seed(123)
# pool=df.f[sample(nrow(df.sel), round(0.2*nrow(df.sel),0)), ]
# pool<-pool[order(pool$SSN),]
# poolid<-pool$SSN


#Get calibration and validation datasets
val_df<-pool
cal_df1 <-subset(df.sel, !(df.sel$SSN %in% val_df$SSN))
# threshold to exclude the extreme 5% values
cal_df <-subset(cal_df1, cal_df1[,2]>quantile(cal_df1[,2], 0.05)&cal_df1[,2] <quantile(cal_df1[,2], 0.95))
val_df1 <-subset(df.sel, (df.sel$SSN %in% val_df$SSN))
val_df <-subset(val_df1, val_df1[,2]>quantile(val_df1[,2], 0.05)&val_df1[,2] <quantile(val_df1[,2], 0.95))
val_df<-val_df[order(rownames(val_df)),]
cal_df<-cal_df[order(rownames(cal_df)),]

#Subset pre-treated spectra by available reference data
val_spec<-spec_trt[is.element(spec_trt$SSN, val_df$SSN),]
cal_spec<-spec_trt[is.element(spec_trt$SSN, cal_df$SSN),]
cal_spec<-cal_spec[order(cal_spec$SSN),]
val_spec<-val_spec[order(val_spec$SSN),]


#Get no of calibration and validation datasets
N_cal<-nrow(cal_spec)
N_val<-nrow(val_spec)

#Model data
Xcal.f=cal_spec[,-1]
Xval.f=val_spec[,-1]
dfcal.f=cal_df[,-1]
dfval.f=val_df[,-1]

###### PLSR SOC
maxc <- 25  ## number of max components
pls.md <- plsr(dfcal.f ~ ., data = Xcal.f, maxc, validation = "CV", segments = 10)#10-fold CV

## plot RMSEP vs. number of components
plot(pls.md, "val", main=slprptr[p]) 

dir.create("Components_plots")
png(paste0(getwd(),"/Components_plots/",slprptr[p],".png"))
print(plot(pls.md, "val", main=slprptr[p]))
dev.off()

## no. components to use, the one with the smallest adj RMSEP value
RMSEP.obj<-RMSEP(pls.md)
str(RMSEP.obj)

RMSEP.obj$val[1:2,1,]
nc <- as.numeric(sub("comps", "", names(which.min(RMSEP.obj$val[1,1,2:dim(RMSEP.obj$val[1:2,1,])[2]]))))
nc

#Generate relevant model name
md.nm<-paste0("pls.md.", slprptr[p], ".nc", nc)

#Rename model with the looped soil property
assign(x = md.nm, value = get("pls.md", pos = .GlobalEnv), pos = .GlobalEnv)

## predict to validation dataset
pls.prd <- predict(pls.md, ncomp = nc, newdata = Xval.f)

## Return prediction statistics
val.stats=round(goof(dfval.f, pls.prd, type = "spec"),3)
val.stats<-bind_cols(Property=paste0(Property=slprptr[p],"_val"), Comps="", N=N_val, val.stats)
val.stats

## calibration statistics
pls.pc <- predict(pls.md, ncomp = nc, newdata = Xcal.f)

pls.cal=round(goof(dfcal.f, pls.pc, type = "spec"),3)
cal.stats<-bind_cols(Property=paste0(Property=slprptr[p],"_cal"), Comps=as.character(nc), N=N_cal, pls.cal)
cal.stats

################### Get model statistics #########################
mdstats<-bind_rows(cal.stats, val.stats)

#Create model stats labels for the plot
slct.stats<-as.data.frame(t(mdstats[,c("Property","Comps","N","R2","RMSE","bias","RPIQ" )]))
names(slct.stats)<-NULL
slct.stats<-bind_cols(rownames(slct.stats),slct.stats[,2])
valbls<-paste0(c("N","R2","RMSE","bias","RPIQ"), "\n")
valsts<-paste0(c(slct.stats[2,2],slct.stats[3,2],slct.stats[4,2],slct.stats[5,2],slct.stats[6,2]))
valstats<-paste(valbls,valsts)

#Bind all looped properties model stats
mdl.stats<-bind_rows(mdl.stats,mdstats)


lgth<-length(sort(dfval.f,decreasing=F))

seq.int(sort(dfval.f,decreasing=F)[1], sort(dfval.f,decreasing=F)[lgth],length.out=4)

#Plot validation plot
plot(dfval.f,pls.prd,pch=10,
     xlab=paste('Measured',names(val_df)[2],sep="_"),
     ylab=paste('Predicted',names(val_df)[2],sep="_"), 
     xlim = range(c(dfval.f,pls.prd)),
     ylim = range(c(dfval.f,pls.prd)),
     mtext(valstats[-1],side=3, at=c(seq.int(sort(dfval.f,decreasing=F)[1], sort(dfval.f,decreasing=F)[lgth],length.out=4)))
     )   ## plot the predicted vs. measured in the validation
abline(a = 0, b = 1)


dir.create("Plots_Validationplots")
png(paste0(getwd(),"/Plots_Validationplots/",slprptr[p],".png"))
print(plot(dfval.f,pls.prd,pch=10,
           xlab=paste('Measured',names(val_df)[2],sep="_"),
           ylab=paste('Predicted',names(val_df)[2],sep="_"), 
           xlim = range(c(dfval.f,pls.prd)),
           ylim = range(c(dfval.f,pls.prd)),
           mtext(valstats[-1],side=3, at=c(seq.int(sort(dfval.f,decreasing=F)[1], sort(dfval.f,decreasing=F)[lgth],length.out=4)))
           ))
abline(a = 0, b = 1)
dev.off()


################### Predict all samples #########################
prd.smpls <- predict(pls.md, spec_trt[,-1])

prd<-as.data.frame(prd.smpls)
df.prd<-bind_cols(SSN=rownames(prd),prd[,nc])
colnames(df.prd)<-c("SSN",slprptr[p])

pred<-merge(pred, df.prd, by="SSN", all.x = T)
}

#Remove the least reliably predicted texture data (Clay,Sand or Silt)
#Recalculate the removed texture data to make Clay+Sand+Silt=100% content

#Write model statistics and predicted values to the local drive
write.csv(mdl.stats, paste0(getwd(),"/Model_Statistics.csv"),row.names = F)
write.csv(pred, paste0(getwd(),"/Predicted_Soil_Properties.csv"),row.names = F)
getwd()



############# Predicting New Spectra Using Existing Models #####################

new_spectra<-read.csv("/Users/vkarari/Library/CloudStorage/OneDrive-CGIAR/Documents/0All_Training/SA_ARC_Physical_Training_Aug-Sept22/ARC-MIR/Argd_Raw_spectra.csv")

wavenumbers <- as.numeric(str_sub(names(new_spectra),2))
names(new_spectra) <- wavenumbers
names(new_spectra)[1] <- "SSN"
rownames(new_spectra)<-new_spectra$SSN


#Pretreat new data as the calibration data was pretreated
co2rem.n<-which((as.numeric(colnames(new_spectra[-1]))) < 2380 & (as.numeric(colnames(new_spectra[-1]))) > 2350)
newspectra.fin<-new_spectra [,-co2rem.n]

spec_vnew.p<-as.data.frame(savitzkyGolay(newspectra.fin[,-1], w=17, p=2, m=1))
spec_vnew.pm<-center_colmeans(spec_vnew.p)


##### Predict new dataset using PLS model: Use the model name suffix as ncomp #####
Clay_pNEW_pls <- as.data.frame(predict(pls.md.Clay.nc11, ncomp = 11, newdata = spec_vnew.pm))

SOC_pNEW_pls <- as.data.frame(predict(pls.md.Carbon.nc14, ncomp = 14, newdata = spec_vnew.pm))

CEC_pNEW_pls <- as.data.frame(predict(pls.md.CEC.nc23, ncomp = 23, newdata = spec_vnew.pm))

PH_H2O_pNEW_pls <- as.data.frame(predict(pls.md.pH_H2O.nc14, ncomp = 14, newdata = spec_vnew.pm))

##################### Predicted dataset using PLSR model
predNEW<-cbind(new_spectra$SSN, Clay_pNEW_pls, SOC_pNEW_pls, CEC_pNEW_pls, PH_H2O_pNEW_pls)

colnames(predNEW) <- c("SSN", "Clay", "SOC", "CEC", "PH_H2O")

write.csv(predNEW,"predicted_pls_all.csv", row.names = F)


```
